coverage:
  precision: 2			# 0 decimals of precision
  round: down           # Round to floor
  range:        		# red -> yellow -> green
  - 60.0
  - 80.0

  status:
    project:
      default:
        # basic
        target: auto
        removed_code_behavior: fully_covered_patch  # see: https://about.codecov.io/blog/new-codecov-setting-removed-code-behavior/
        threshold: 1%		# allow 1% coverage variance, because depending on the run, different OSes results are uploaded for each run and some code is OS-specific, so this is it's within expected OS-dependent variability
