coverage:
  precision: 0			# 0 decimals of precision
  round: nearest        # Round to nearest precision point
  range: "50...80"		# red -> yellow -> green

  status:
    project:
      default:
        # basic
        target: auto
        removed_code_behavior: fully_covered_patch  # see: https://about.codecov.io/blog/new-codecov-setting-removed-code-behavior/
        threshold: 1%		# allow 1% coverage variance, because depending on the run, different OSes results are uploaded for each run and some code is OS-specific, so this is it's within expected OS-dependent variability

    patch:
      default:
        threshold: 1%		# allow 1% coverage variance
